language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - python setup.py install
  - pip install Flask-SQLAlchemy
# command to run tests
script: nosetests 
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek"
